import turtle 

bot = turtle.Turtle() 
step =(50) 
turnAngle =90 
bot.color("red") 
bot.begin_fill()
bot.pencolor("red") 
bot.forward(step) 
bot.right(turnAngle) 
bot.forward(step) 
bot.right(turnAngle) 
bot.forward(step) 
bot.left(turnAngle) 
bot.forward(step) 
bot.right(turnAngle) 
bot.forward(step) 
bot.right(turnAngle) 
bot.forward(step) 
bot.left(turnAngle)
bot.forward(step) 
bot.right(turnAngle) 
bot.forward(step) 
bot.right(turnAngle) 
bot.forward(step) 
bot.left(turnAngle)
bot.forward(step) 
bot.right(turnAngle) 
bot.forward(step) 
bot.right(turnAngle) 
bot.forward(step) 
bot.left(turnAngle) 
bot.end_fill()